create table "public"."task_completion_history" (
    "id" bigint generated by default as identity not null,
    "task_id" bigint not null,
    "completed_at" timestamp with time zone not null default now()
);


CREATE INDEX idx_task_completion_history_task_id ON public.task_completion_history USING btree (task_id);

CREATE UNIQUE INDEX task_completion_history_pkey ON public.task_completion_history USING btree (id);

alter table "public"."task_completion_history" add constraint "task_completion_history_pkey" PRIMARY KEY using index "task_completion_history_pkey";

alter table "public"."task_completion_history" add constraint "task_completion_history_task_id_fkey" FOREIGN KEY (task_id) REFERENCES tasks(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."task_completion_history" validate constraint "task_completion_history_task_id_fkey";

grant delete on table "public"."task_completion_history" to "anon";

grant insert on table "public"."task_completion_history" to "anon";

grant references on table "public"."task_completion_history" to "anon";

grant select on table "public"."task_completion_history" to "anon";

grant trigger on table "public"."task_completion_history" to "anon";

grant truncate on table "public"."task_completion_history" to "anon";

grant update on table "public"."task_completion_history" to "anon";

grant delete on table "public"."task_completion_history" to "authenticated";

grant insert on table "public"."task_completion_history" to "authenticated";

grant references on table "public"."task_completion_history" to "authenticated";

grant select on table "public"."task_completion_history" to "authenticated";

grant trigger on table "public"."task_completion_history" to "authenticated";

grant truncate on table "public"."task_completion_history" to "authenticated";

grant update on table "public"."task_completion_history" to "authenticated";

grant delete on table "public"."task_completion_history" to "service_role";

grant insert on table "public"."task_completion_history" to "service_role";

grant references on table "public"."task_completion_history" to "service_role";

grant select on table "public"."task_completion_history" to "service_role";

grant trigger on table "public"."task_completion_history" to "service_role";

grant truncate on table "public"."task_completion_history" to "service_role";

grant update on table "public"."task_completion_history" to "service_role";


